### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by chrisbell08**
#3 Fix for this issue

### CODE REVIEW

**Comment by dan-gamble** [comment]
Awesome thank you! Wasn't aware i had to have the output escaped but it makes sense now. I'll merge and fix the test myself. Thanks again :)

**Comment by chrisbell08** [comment]
No Probs, I was just about to write my own one of these so finding yours first saved me a bunch of time!

**Comment by dan-gamble** [comment]
Sweet! I was gonna do a few more for some other font icon sets as well, just not sure what people use as well as font-awesome

**Comment by chrisbell08** [comment]
I can't help i'm afraid I only really use Font Awesome

**Pull request merged**
