### PR TITLE
fix: seems to not work - needs to be a post install

### PR DESCRIPTION
**Pull request by maraisr**
Sorry mate....

### CODE REVIEW

**Comment by dan-gamble** [comment]
No worries, will merge and push again 👍

**Comment by maraisr** [comment]
Might need to chat to you about this - you know how when you `npm i` im getting an

``` sh
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--unsafe-perm"
npm ERR! node v6.2.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! postcss-font-awesome@0.3.1 postinstall: `node ./generateIconConfig.js`
npm ERR! Exit status 1
```

which to me feels like the `npmignore` is blocking the `generateIconConfig.js` file potentially?

**Comment by dan-gamble** [comment]
Sounds like a likely cause to me, i've just pushed a release that has that removed from `npmignore`, do you wanna try that?

**Comment by maraisr** [comment]
Perfect mate!! Love your work!!

_They dont make it easy do that!! hahah_

**Comment by dan-gamble** [comment]
Ha, it's just as much yours as it is mine now :D

**Pull request merged**
